config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get '/', to: "static_page#home"
  get '/home', to: 'static_page#home'
  get '/help', to: 'static_page#help'
  get '/contact', to: 'static_page#contact'
  get '/signup', to: 'users#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i 
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def show
    @user = User.find(params[:id])
   

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase) 
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}" 
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
    <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a> 
    </small>
    <nav> 
        <ul>
            <li><%= link_to "About", '#' %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul> 
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"> 
    <div class="container">
        <%= link_to "sample app", 'home', id: "logo" %> 
        <nav>
            <ul class="nav navbar-nav navbar-right"> 
                <li><%= link_to "Home", 'home' %></li> 
                <li><%= link_to "Help", 'help' %></li> 
                <li><%= link_to "Log in", 'signup' %></li>
            </ul> 
        </nav>
    </div> 
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "footer", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%=render 'layouts/rails_default'%>
    <%=render 'layouts/shim'%>
  </head>

  <body>
    <%=render 'layouts/header' %>
    <div class="container"> 
      <%= yield %>
    </div>
    <%=render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/static_page/contact.html.erb
<%=provide(:title, "Contact") %>
<h1>StaticPage#contact</h1>
<p>Find me in app/views/static_page/contact.html.erb</p>

app/views/static_page/help.html.erb
<%=provide(:title, "Help")%>
<h1>StaticPage#help</h1>
<p>Find me in app/views/static_page/help.html.erb</p>

app/views/static_page/home.html.erb
<%=provide(:title, "Home")%>
<div class="center jumbotron"> 
    <h1>Welcome to the Sample App</h1>
    <h2>
        This is the home page for the
        <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
    </h2>
    <%= link_to "Sign up now!", 'signup', class: "btn btn-lg btn-primary" %> 
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>

app/views/users/new.html.erb
<%=provide(:title, 'SignUp')%>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> 
<h1>
    <%= gravatar_for @user %>
    <%= @user.name %> 
    <%= @user.email %> 
</h1>